name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from your upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          
          upstream_sync_repo: ShivKumard0/SmartDocsAI-Source
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "::error::Sync failed due to permission or conflict. Consider running it manually."
          exit 1
